name: Liting and Artifact generation

on:
  push:
    tags-ignore:
      - '**'
  pull_request:

jobs:
    Lint-Project:
      name: "Linting and Artifact generation for push"
      if: startsWith(github.ref, 'refs/tags/v') == false
      runs-on: ubuntu-latest
      steps:
       - name: "Update Image"
         if: ${{ env.ACT }}
         run: |
            sudo apt update
       - uses: actions/checkout@v4
         with:
           fetch-depth: 50
       - name: Lint lua files
         uses: nebularg/actions-luacheck@v1.1.2
         with:
           args: "--no-color -q --no-self"
           annotate: warning
       - name: Create alpha package
         uses: BigWigsMods/packager@master
         with:
            args: -d -z
       - name: Upload alpha package to artifacts
         uses: actions/upload-artifact@v3
         with:
           name: CompanionsTracker
           path: |
             .release/*
       - name: Remove old artifacts
         uses: c-hive/gha-remove-artifacts@v1
         with:
           age: '3 month'
           skip-tags: true
